export { collectCandidateNodes, locateSection } from "./sectionLocate.js";
export type { SectionLocateOptions, SectionLocateResult } from "./sectionLocate.js";
export { capturePageStructure, crawlNavMap, visitEntry } from "./navMapCrawl.js";
export type { NavMapCrawlOptions } from "./navMapCrawl.js";
export { DEFAULT_NAV_MAP_SWEEP_BATCH_SIZE, pickStalestNavMapEntries, sweepNavMapEntries } from "./navMapSweep.js";
export type { NavMapSweepOptions } from "./navMapSweep.js";
export { researchSection } from "./research.js";
export { renderResearchMarkdown } from "./researchMarkdown.js";
export { buildTestPlan } from "./testPlan.js";
export type { TestPlanOptions } from "./testPlan.js";
export { renderTestPlanMarkdown } from "./testPlanMarkdown.js";
export { judgeOutcome } from "./outcomeJudge.js";
export type { OutcomeJudgeInput, OutcomeJudgeOptions, OutcomeJudgeResult } from "./outcomeJudge.js";
export { executeHappyPathCheck } from "./happyPathExecutor.js";
export type { HappyPathCheckInput, HappyPathCheckResult } from "./happyPathExecutor.js";
export { executeBoundaryCheck } from "./boundaryExecutor.js";
export type { BoundaryCheckInput, BoundaryCheckResult } from "./boundaryExecutor.js";
export { generateMarker, injectMarker, selectFreeTextField } from "./marker.js";
export { rollback } from "./rollback.js";
export type { RollbackLocator, RollbackOptions, RollbackResult } from "./rollback.js";
export { buildRunContext, refreshLearningConfirmations } from "./learningContext.js";
export type { LearningRepoLike } from "./learningContext.js";
export { injectLearning, recordFeedback } from "./feedback.js";
export type { FeedbackVerdict, FindingRepoLike, InjectLearningInput, RecordFeedbackInput } from "./feedback.js";
export { detectDrift } from "./drift.js";
export type { DriftFlag } from "./drift.js";
export { buildCheckExecutionErrorResult, classifyCheckExecutionError } from "./checkExecutionError.js";
export type { CheckExecutionErrorInput } from "./checkExecutionError.js";
export { trackClientUsage } from "./usageTracking.js";
export type { TrackedClientFactory, UsageTotals } from "./usageTracking.js";
export { generateFeatureDocument } from "./featureDocumentGenerator.js";
export type { FeatureDocumentGeneratorOptions, FeatureDocumentGenerationResult } from "./featureDocumentGenerator.js";
export { buildStepFailureFinding, executeSessionReplayStep } from "./sessionReplayExecutor.js";
export type { SessionReplayStepInput, SessionReplayStepResult } from "./sessionReplayExecutor.js";
